name: Production CI

on:
  push: 
    branches:
      - main

jobs:
  job_1:
    name: Job 1
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    - name: output
      id: output_1
      run: |
        echo "output 1"
      shell: bash