name: Staging CI
author: Howard
description: |
  This is a test workflow to test the environment variable
  in the staging environment.

on:
  push: 
    branches:
      - main

jobs:
  job_1:
    name: Job 1
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - uses: actions/checkout@v3
    - name: Output
      id: output_1
      run: |
        echo "${{ secrets.TEST_VAR }}"
      shell: bash